baseURL: 'http://localhost:1313/'
languageCode: pt-br
theme: tema-da-lepidus
title: Lepidus Tecnologia

params:
  images:
    logoLepidus: /images/Banner_Lepidus_Tecnologia.svg
    logoPeriodicos: /images/Periodicos-em-Nuvens.png
    logoEventos: /images/Eventos-em-Nuvens.png
    logoGrupos: /images/Grupos-em-Nuvens.png

menu:
  nav:
  - name: Inicio
    url: /
    weight: 1
  - name: Quem somos
    url: /quem-somos/
    weight: 2
  - name: Periódicos em Nuvens
    url: /periodicos-em-nuvens/
    weight: 3
  - name: Eventos em Nuvens
    url: /eventos-em-nuvens/
    weight: 4
  - name: Grupo em Nuvens
    url: /grupos-em-nuvens/
    weight: 5
  - name: Fale Conosco
    url: /contato/
    weight: 6